url: https://edwardsfarmvt.com
#baseurl: /info # the subpath of your site, e.g. /blog
title: "Edward's Farm" # the name of your site, e.g. ACME Corp.
github_pages: true
#sass:
#  sass_dir: assets/css/_scss
# bundle exec jekyll serve --livereload
#lsi: false
#safe: true
#source: info
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
